local input
local output
local name

local i = 1
while i <= select('#', ...) do
    local argv = select(i, ...)
    if argv == '-n' then
        i = i + 1
        name = select(i, ...)
    elseif argv == '-o' then
        i = i + 1
        output = select(i, ...)
    else
        input = argv
        break
    end
    i = i + 1
end

local fh = assert(io.open(input, "rb"))
local total = {}
local len = 0
local t = {}
local col = 0
local s = ""
while true do
    local s = fh:read(1024)
    if not s then break end
    len = len + #s
    for m in s:gmatch "." do
        if m:match "[\\\"\n\r\t]" then
            if     m == '\n' then t[#t+1] = '\\n'
            elseif m == '\r' then t[#t+1] = '\\r'
            elseif m == '\t' then t[#t+1] = '\\t'
            else                  t[#t+1] = '\\'..m
            end
            col = col + 2
        elseif m:match "%G" and m ~= ' ' then
            t[#t+1] = ("\\%03o"):format(string.byte(m))
            col = col + 4
        else
            t[#t+1] = m
            col = col + 1
        end
        if col >= 76 then
            total[#total+1] = '    "'..table.concat(t)..'"\n'
            t = {}
            col = 0
        end
    end
end
fh:close()

total[#total+1] = '    "'..table.concat(t)..'"'

io.output(output)

io.write((([[
/*
 * auto-generated by txt2c.lua
 */
#include <stddef.h> /* for size_t */

const char $(name)[] = 
$(value);

size_t $(name)_len = $(len);

/* end of file */
]]):gsub('$%((%w+)%)', {
    name = name,
    value = table.concat(total),
    len = len,
})))
